<?=$this->partial('/partial/home-top')?>
<body id="app">
      <?php echo $this->partial('/home/home/tpl/theme-options') ?>
      <div id="texture">
       <!-- start HEADER -->
<section id="top" class="page-block">
  <header id="home">
    <div class="container clearfix">
      <div class="navigation">
        <div class="row">
          <div class="col-md-4 col-sm-3">
            <h1 class="logo"><a href="index.html" title="Primo"><img class="img-responsive" src="/grupo-suricatis-admin/img/brand.png" alt="OnEvent"></a></h1>
          </div>
          <div class="col-md-8 col-sm-9"> 
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar navbar-default navbar-header visible-xs" role="navigation">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#Navigation"> 
                  <span class="icon-bar"></span> 
                  <span class="icon-bar"></span> 
                  <span class="icon-bar"></span> 
              </button>
            </div>
            <nav>
              <ul id="Navigation" class="list-inline collapse navbar-collapse">
                <li><a href="<?=$this->url('home')?>" title="Pagina Inicial">HOME</a></li>
                <li><a href="<?=$this->url('home-site')?>#schedule" title="Conograma">CONOGRAMA</a></li>
                <li><a href="<?=$this->url('home/default',['controller'=>'home','action'=>'termos-de-uso'])?>" title="Termos De Uso">TERMOS DE USO</a></li>
                <li><a href="<?=$this->url('home/default',['controller'=>'home','action'=>'politica-de-privacidade'])?>" title="Politica de Privacidade">POLITICA DE PRIVACIDADE</a></li>
                <li><a href="<?=$this->url('home-site')?>#venue" title="Encontre-nos">LOCALIZAÇÃO/CONTATO</a></li>
              </ul>
            </nav>
          </div>
          <!-- end col-md-10 --> 
        </div>
        <!--end-row--> 
      </div>
      <!-- end navigation --> 
    </div>
    <!-- end container --> 
  </header>
  </section>

<?= $this->content ?>

<?=$this->partial('/partial/home-button')?>
</body>
</html>